### ISSUE TITLE
Implement Server/Service for Login

### ISSUE THREAD

**Issue by eddyw** [chingu-coders/Voyage2-Bears-24#19]
_User Story:_

**As a** developer, **I want to** have a Service for `/login` path **so that I** implement a log in form and dashboard users can log in

_Acceptance Criteria:_

- [x] Create a Service under `./controller/login.js`
- [x] Add an event listener named `login`
  - [x] It should verify if the username and password given match or exist

_Depends on:_
Task #15  needs to be completed in order to proceed with this task

**Comment by gregorywong** [comment]
@eddyw I started looking at this issue and I don't think I know what I'm doing.

So far my understanding is this:
1. To create a Service, I have to start with `class Login extends ServerNameSpace`, similar to what we do in `./controller/main.js`.
1. Once I receive an event `login`, I should call the model DashboardUsers to check if the username and password are a match. But I don't know how to add an event listener.

Can you help shed some light on the issue?

**Comment by eddyw** [comment]
@gregorywong Brian is working on task #15 which needs to be resolved first in order to proceed with this task.

**Comment by cbchien** [comment]
task #15 is complete
