### ISSUE TITLE
Implement a Log In form

### ISSUE THREAD

**Issue by eddyw** [chingu-coders/Voyage2-Bears-24#20]
_User Story:_

**As a** non-logged user, **I want to** see a login form **so that I** introduce my username and password to enter the dashboard

_Acceptance Criteria:_

- [x] I should have a Page Component in `./client/view/Login`
  - [x] It should have a field for username and password
- [x] Add a route for `/login` in `./client/index.js`

**Comment by gregorywong** [comment]
@eddyw I'm not sure how to add a route (without overwriting the existing `/setup` route). But I've added the login form (with lots of room for improvement).
https://github.com/chingu-coders/Voyage2-Bears-24/tree/feat/S2-020-login-form
Can you advise how the route adding should be done?

**Comment by eddyw** [comment]
@gregorywong yes, `<Router/>` expects to have only one element as children. If you have more than one Route you have to wrap them into another component or element.
Added route! check it please.
Besides that, I made some changes such as adding background picture (blank background looks so ugly haha) and I removed the header from the login form since it's not needed (the user is not logged in) and added the logo to the form itself.
Please, check that too. Then, make a PR.

**Comment by eddyw** [comment]
@gregorywong actually, what about removing `Forgot password` and `Remember me`.
Password is set in the `Settings > users` doc, so the person who has access to this document can modify a user's password. Anyway, it's not really important.
About `Remember me`, I am actually not so sure..

**Comment by gregorywong** [comment]
Wow, it looks so much better with the background!

I guess there's no need to include `Forgot password` and `Remember me` then. If they really want it, they can request it later on.

I'll remove those and make a PR.

**Comment by gregorywong** [comment]
@eddyw Wow, it looks so much better with the background!

I guess there's no need to include `Forgot password` and `Remember me` then. If they really want it, they can request it later on.

I've removed those and made a PR.
