### ISSUE TITLE
Implement a Sidebar and MainContent components

### ISSUE THREAD

**Issue by eddyw** [chingu-coders/Voyage2-Bears-24#25]
_User Story:_

**As a** developer, **I want to** be able to see a sidebar along a main content layout **so that I** navigate through the application using the sidebar and display a page's content in the main layout

_Acceptance Criteria:_

- [x] I should have a Sidebar Component
  - [x] It should accept a property sections (props.sections)
    - [x] `props.sections` will be an array of object in this format `[{ item: 'Title of item', path: '/page' },...]`
  - [x] It should be connected to React Router
  - [x] It should generate the list of item from `props.sections` array
  - [x] when I click on an item, it should redirect to the `path` specified

**Comment by cbchien** [comment]
complete
