### ISSUE TITLE
M3 - Team expectations

### ISSUE THREAD

**Issue by eddyw** [chingu-coders/Voyage2-Bears-24#3]
**Team Expectations**

Please fill out **your** section in this Google doc.
https://docs.google.com/document/d/1WX5Wc_WCCLJWBuf6vVlyCNWCuwMyRlkBeGL2kRhEYEs/edit#
- [x] @cbchien 
- [x] @gregorywong 
- [x] @eddyw

**Comment by gregorywong** [comment]
**Questions to answer:**

1. How do you think this experience will benefit you?

1. What is your coding experience?

1. How many hours can you devote to this project per week?

1. Can we count on you to complete your twice weekly check-ins?

**Comment by gregorywong** [comment]
@eddyw @cbchien 
I have two ideas on how we should do all of this in an organized way.

1. Have everyone fill in their section on Google docs. It would be easier to organize and refer to later on. If necessary, we can migrate it somewhere else at a later stage. It's just text mostly.
1. Do it directly in GitHub, perhaps in the wiki, or even under issues. Possibly more messy.

Thoughts?

**Comment by cbchien** [comment]
comments added

**Comment by eddyw** [comment]
Done! Task completed.

**Comment by gregorywong** [comment]
👏 👏 👏
