### ISSUE TITLE
Create README file

### ISSUE THREAD

**Issue by gregorywong** [chingu-coders/Voyage2-Bears-24#5]

**Comment by eddyw** [comment]
@gregorywong please check:
https://github.com/chingu-coders/Voyage2-Bears-24/projects/2
I created a task in the Project's dashboard. Let's not create a task for each added file for the initial setup. Instead, a single task with basic set up. After, new tasks can be created to make other changes to the initial set up.
I will include in the `collaborating-guide.md` a guide of how to create tasks in the Projects board. This issue (#5) is not tracked in the Projects board, for instance.

**Comment by gregorywong** [comment]
@eddyw Sure thing. Thanks for setting it up!
