### ISSUE TITLE
Initial Project Set Up

### ISSUE THREAD

**Issue by eddyw** [chingu-coders/Voyage2-Bears-24#6]
_User Story:_

**As I** developer, **I want to** have a initial set up **so that I can** start working on the project once the Act's milestones are complete

_Acceptance Criteria:_

- [x] Have a `README.md` file
- [x] Have a `LICENSE.md` file. MIT License is used and the names of the creators of the project are shown
- [x] Have a `CONTRIBUTING.md` file containing conventions to be used and a guide of how to's
- [x] Initialize a new project `npm init`
- [x] Set up `package.json` properly (name, description, authors, github url)
- [x] Set up Webpack with `ts-loader`
- [x] Add and set up a `ts-config.json` file to transpile from es6 to es5 (Including JSX and support for decorator functions)

**Comment by gregorywong** [comment]
@eddyw Can we rename `COLLABORATOR-GUIDE.md` to `CONTRIBUTING.md` instead? That way, it will show up automatically whenever someone creates and issue or pull request. See this link: https://github.com/blog/1184-contributing-guidelines

**Comment by eddyw** [comment]
@gregorywong got it!
